### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by di48l069** [YodasMyDad/mvcforum#97]
Hi,

Would it not be better if you implement `google translate` into the forum and the user can translate the forum with there desired language this will be saved in there profile?

Instead of setting the entire forum one language.

**Comment by LeiYangGH** [comment]
chrome itself can translate any page without web's own built in functions, i think.

**Comment by di48l069** [comment]
@LeiYangGH Possibly but I don't use chrome and not everyone uses chrome

**Comment by LeiYangGH** [comment]
All Chinese not use google.

**Comment by di48l069** [comment]
@LeiYangGH So I have heard

**Comment by wezmag** [comment]
@LeiYangGH Not all Chinese do not/can not use Google. Only people in Mainland China can not access google.com due to the [Great Firewall of China](https://en.wikipedia.org/wiki/Great_Firewall). [Here is a list of sites that is blocked by Chinese government](https://en.wikipedia.org/wiki/Websites_blocked_in_mainland_China). For those people who want to use Google, they can always use VPN. BTW, I am from [Taiwan](https://en.wikipedia.org/wiki/Taiwan) which is not part of China and I use Google everyday.
